// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM09ZkyUtb3HkiaI64WyAup2nAwG1S1Zc',
    appId: '1:538822780662:web:529932010dac68caa6eed7',
    messagingSenderId: '538822780662',
    projectId: 'flutter-prep-479ff',
    authDomain: 'flutter-prep-479ff.firebaseapp.com',
    databaseURL: 'https://flutter-prep-479ff-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-479ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLGqECDuYRLhtkjJQQBohHSAXYDhIFYc',
    appId: '1:538822780662:android:8b67190b554aa539a6eed7',
    messagingSenderId: '538822780662',
    projectId: 'flutter-prep-479ff',
    databaseURL: 'https://flutter-prep-479ff-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-479ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZryQCEf-WgYip_i74E632URN-6sDkrw',
    appId: '1:538822780662:ios:2a0f64d68a7bcb8ca6eed7',
    messagingSenderId: '538822780662',
    projectId: 'flutter-prep-479ff',
    databaseURL: 'https://flutter-prep-479ff-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-479ff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZryQCEf-WgYip_i74E632URN-6sDkrw',
    appId: '1:538822780662:ios:2a0f64d68a7bcb8ca6eed7',
    messagingSenderId: '538822780662',
    projectId: 'flutter-prep-479ff',
    databaseURL: 'https://flutter-prep-479ff-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-479ff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM09ZkyUtb3HkiaI64WyAup2nAwG1S1Zc',
    appId: '1:538822780662:web:86acc57949f6ea5aa6eed7',
    messagingSenderId: '538822780662',
    projectId: 'flutter-prep-479ff',
    authDomain: 'flutter-prep-479ff.firebaseapp.com',
    databaseURL: 'https://flutter-prep-479ff-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-479ff.appspot.com',
  );
}
